[package]
name = "foxbox"
version = "0.1.0"
authors = ["fabrice <fabrice@desre.org>"]
build = "build.rs"

[dependencies]
clippy = "0.0.37"
docopt = "0.6.78"
docopt_macros = "0.6.80"
env_logger = "0.3.2"
hyper = "0.7"
iron = "0.2.6"
log = "0.3"
mio = { git = "https://github.com/carllerche/mio.git" }
mount = "0.0.10"
router = "0.1.0"
rustc-serialize = "0.3"
serde = "0.6.11"
serde_json = "0.6.0"
serde_macros = "0.6.11"
staticfile = "0.1.0"
uuid = "0.1.18"
websocket = "0.15"
ws = "0.4"
